### ISSUE TITLE
MP里面的自动获取插件没用，一直卡在开始请求企业微信管理更改可信IP

### ISSUE THREAD

**Issue by AWdress** [suraxiuxiu/WeworkAutoIpConfig#1]
【INFO】2024-05-29 22:27:37,998 - weworkip - 开始请求企业微信管理更改可信IP
【INFO】2024-05-29 22:27:37,997 - weworkip - 检测到IP变化
【INFO】2024-05-29 22:27:37,997 - weworkip - IP获取成功: https://myip.ipip.net: 49.89.234.221
【INFO】2024-05-29 22:27:36,649 - weworkip - 检测公网IP中
【INFO】2024-05-29 22:27:33,647 - weworkip - 立即检测公网IP
【INFO】2024-05-29 22:20:38,538 - weworkip - 开始请求企业微信管理更改可信IP
【INFO】2024-05-29 22:20:38,537 - weworkip - 检测到IP变化
【INFO】2024-05-29 22:20:38,537 - weworkip - IP获取成功: https://myip.ipip.net: 49.89.234.221
【INFO】2024-05-29 22:20:36,849 - weworkip - 检测公网IP中
【INFO】2024-05-29 22:20:33,846 - weworkip - 立即检测公网IP
【INFO】2024-05-29 22:16:41,256 - weworkip - 开始请求企业微信管理更改可信IP
【INFO】2024-05-29 22:16:41,256 - weworkip - 检测到IP变化
【INFO】2024-05-29 22:16:41,255 - weworkip - IP获取成功: https://myip.ipip.net: 49.89.234.221
【INFO】2024-05-29 22:16:39,639 - weworkip - 检测公网IP中
【INFO】2024-05-29 22:16:36,638 - weworkip - 立即检测公网IP

企业微信可信IP 也没有改动

**Comment by DongShull** [comment]
是啊，失效了，总是cookie失效

**Comment by suraxiuxiu** [comment]
> 是啊，失效了，总是cookie失效

还在测试一些失效的情况,后面会推出一个相对稳定的版本
