### ISSUE TITLE
爱快多拨IP容易失效

### ISSUE THREAD

**Issue by saarjoye** [suraxiuxiu/WeworkAutoIpConfig#2]
大佬能解决一下吗？
多拨后。同步了IP A进了企微后台。但是企微给IP B推送

**Comment by suraxiuxiu** [comment]
> 大佬能解决一下吗？ 多拨后。同步了IP A进了企微后台。但是企微给IP B推送

这个情况建议从爱快入手解决吧  让设备走指定wan  或者设置用静态路由让ip检测网址走IP B出口 
然后用DDNS GO或者类似的功能把IP B固定到企微推送的域名上  这样应该能保证两边都用IP B了  
对网络懂的不多 不一定正确  你参考下
