### ISSUE TITLE
群晖MOVIEPILOT套件使用企微自动配置IPpw版 v1.1报错，没有该目录

### ISSUE THREAD

**Issue by ymtw** [suraxiuxiu/WeworkAutoIpConfig#4]
weworkippw - cookie校验失败:ENOENT: no such file or directory, mkdtemp '/var/packages/MoviePilot/target/tmp/playwright-artifacts-O8Fk7A'

**Comment by l429609201** [comment]
大佬，我想问一下，py项目还更新吗？MP的插件版本无法使用，truenas系统使用k3s，没法将容器接口映射进去，日志报错
如下
【INFO】2024-10-06 09:17:38,954 - weworkippw - 检测公网IP完毕
【ERROR】2024-10-06 09:17:38,954 - weworkippw - 请求企微失败,cookie可能过期,跳过IP检测
============================================================
[pid=18144][err] [18144:18144:1006/091738.779771:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
[pid=18144][err] [18144:18144:1006/091738.779703:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[pid=18144][err] [18144:18158:1006/091738.220473:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
<launched> pid=18144
<launching> /moviepilot/.cache/ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-JQzLRY --remote-debugging-pipe --no-startup-window
=========================== logs ===========================
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
║ <3 Playwright Team                                                                             ║
║                                                                                                ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║ Looks like you launched a headed browser without having a XServer running.                     ║
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
【ERROR】2024-10-06 09:17:38,953 - weworkippw - cookie校验失败:
【INFO】2024-10-06 09:17:31,061 - weworkippw - 开始检测公网IP
【INFO】2024-10-06 09:17:28,059 - weworkippw - 立即检测公网IP

**Comment by suraxiuxiu** [comment]
> # 大佬，我想问一下，py项目还更新吗？MP的插件版本无法使用，truenas系统使用k3s，没法将容器接口映射进去，日志报错
> 如下
> 【INFO】2024-10-06 09:17:38,954 - weworkippw - 检测公网IP完毕
> 【ERROR】2024-10-06 09:17:38,954 - weworkippw - 请求企微失败,cookie可能过期,跳过IP检测
> [pid=18144][err] [18144:18144:1006/091738.779771:ERROR:env.cc(255)] The platform failed to initialize. Exiting. [pid=18144][err] [18144:18144:1006/091738.779703:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY [pid=18144][err] [18144:18158:1006/091738.220473:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory pid=18144 /moviepilot/.cache/ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-JQzLRY --remote-debugging-pipe --no-startup-window =========================== logs =========================== ╚════════════════════════════════════════════════════════════════════════════════════════════════╝ ║ <3 Playwright Team ║ ║ ║ ║ Set either 'headless: true' or use 'xvfb-run ' before running Playwright. ║ ║ Looks like you launched a headed browser without having a XServer running. ║ ╔════════════════════════════════════════════════════════════════════════════════════════════════╗ 【ERROR】2024-10-06 09:17:38,953 - weworkippw - cookie校验失败: 【INFO】2024-10-06 09:17:31,061 - weworkippw - 开始检测公网IP 【INFO】2024-10-06 09:17:28,059 - weworkippw - 立即检测公网IP

修复了  试试看最新版
